### ISSUE TITLE
HTTP(S) Proxy Support

### ISSUE THREAD

**Issue by 195858** [SolaceLabs/ep-openapi-typescript#7]
Can we add support for the client to use an outbound HTTP proxy if the appropriate env variables are defined?

I'd suggest to use `fetch-with-proxy` - https://www.npmjs.com/package/fetch-with-proxy.
It allows to set the proxy via env variables (see link above)
The following change would be required to import statements in request.ts:
Instead of - 
```
import fetch, { BodyInit, Headers, RequestInit, Response } from 'node-fetch';
```
use the fetch function from `fetch-with-proxy`:
```
import { BodyInit, Headers, RequestInit, Response } from 'node-fetch';
import fetch from 'fetch-with-proxy';
```

**Comment by ricardojosegomezulmke** [comment]
added in new release.
