### ISSUE TITLE
Use a resolver for Base URI in OpenAPI Config

### ISSUE THREAD

**Issue by 195858** [SolaceLabs/ep-openapi-typescript#8]
Need to resolve/set the base URL dynamically from current context of execution in safe manner.

Can we use a resolver for the `BASE` property in addition to the `string` type that is currently declared  in the `Config` type 
(contained in `OpenAPI.ts` in the generated code)?

The following changes are required:

**OpenAPI.ts**

Add `| Resolver<string>` t the BASE declaration
```
type Config = {
    BASE: string | Resolver<string>;
    VERSION: string;
    WITH_CREDENTIALS: boolean;
    TOKEN?: string | Resolver<string>;
    USERNAME?: string | Resolver<string>;
    PASSWORD?: string | Resolver<string>;
    HEADERS?: Headers | Resolver<Headers>;
}
```

**request.ts**

Change the `getUrl` function to treat OpenAPI.BASE as a resolver and declare it as `async`:
```
async function getUrl(options: ApiRequestOptions): Promise<string> {
    const path = options.path.replace(/[:]/g, '_');
    const base = await resolve(options, OpenAPI.BASE);
    const url = `${base}${path}`;

    if (options.query) {
        return `${url}${getQueryString(options.query)}`;
    }
    return url;
}
```

Also the call to `getUrl` needs to use `await`:
```
export async function request(options: ApiRequestOptions): Promise<ApiResult> {
    const url = await getUrl(options);
```

**Comment by 195858** [comment]
Here is an example of how this can be applied:

https://github.com/solace-iot-team/platform-api/blob/main/api-implementation/src/clients/eventportal/core/OpenAPI.ts

https://github.com/solace-iot-team/platform-api/blob/main/api-implementation/src/clients/eventportal/core/request.ts

**Comment by 195858** [comment]
Here is an example of how to use the resolver in code

** declare a resolver function**

```
export async function getBaseUrl(): Promise<string> {
  let url: string = null;
  // set url - database lookup, lookup from context etc
   return url;
 }
```


** set the resolver on the OpenAPI Config object**

```
import { getBaseUrl } from './urlhelper';
```
[...]
```
  constructor() {
    OpenAPI.BASE = getBaseUrl;
  }
```

Usage example:
https://github.com/solace-iot-team/platform-api/blob/main/api-implementation/src/cloudtokenhelper.ts
https://github.com/solace-iot-team/platform-api/blob/main/api-implementation/src/eventportalfacade.ts

**Comment by ricardojosegomezulmke** [comment]
added in new release.
